### ISSUE TITLE
[Error] SyntaxError: Invalid regular expression: invalid group specifier name (anonymous function) (mojocss.min.js:2) on Safari IOS v15 and v16

### ISSUE THREAD

**Issue by webcodavic** [mojocss/mojocss#13]
I got this error on Safari IOS v15 and v16 and it causes mojocss not to load

**Comment by webcodavic** [comment]
The use of lookbehinds `((?<!calc\())` is not supported by Safari iOS v15. When I removed the `<` between `?` and `!` it works fine

`/(?<!calc\()var\(--\w+?(?:-\w+?)*\)(?!\))|[+\-*/]/g`
with
`/(?!calc\()var\(--\w+?(?:-\w+?)*\)(?!\))|[+\-*/]/g `

**Comment by ali-m97** [comment]
Hi,
Thanks for the bug report, we will fix it in the update

**Comment by ali-m97** [comment]
This issue is fixed in 0.2 RC version
