### ISSUE TITLE
Typo in Installation Guide

### ISSUE THREAD

**Issue by amirhoseinsalimi** [mojocss/mojocss#2]
Hey, thank you for the great job. I haven't spent much time on the framework, but I know that a lot has been done. Well done.

However, I noticed a typo in the installation guide as shown in the screenshot below (`import mojo from from 'mojocss'`):

![IMG_20240207_000220.jpg](https://github.com/mojocss/mojocss/assets/25503371/5dc0f85a-d95f-4b04-99b9-1fa8d2c9f787)

The link to this typo is [here](https://mojocss.com/docs/guide/installation).

**Comment by ali-m97** [comment]
Hi,
problem solved
Thank you
