### ISSUE TITLE
Arbitrary value with brackets within arbitrary attribute doesn't work

### ISSUE THREAD

**Issue by webcodavic** [mojocss/mojocss#20]
Example
_="(.FancySelect__control:hover) border-c-(var(--brand-color)) shadow-(0_0_0_1px_var(--brand-color))"

How the above rule border color generated
![image](https://github.com/mojocss/mojocss/assets/152366515/9c931e30-4005-483c-b07f-0733c4d69ae3)

Checking on dev tools
![image](https://github.com/mojocss/mojocss/assets/152366515/ef30d574-f7f5-4b34-9bcf-c3b6065f6cfb)

**Comment by ali-m97** [comment]
Hi
This problem is now fixed in RC version. Please test that with `npm i mojocss@next`.
Thank you
