### ISSUE TITLE
d-flex and grid

### ISSUE THREAD

**Issue by santiagodonoso** [mojocss/mojocss#25]
To use flexbox, we need to write "d-flex".
To use grid, we need to just write "grid".

Why not just use "flex" instead of "d-flex" ?

**Comment by ali-m97** [comment]
Hi,
`d-` is a dynamic utility used to set the `display` property. However `grid` is a static utility that, in addition to setting the `display` property also sets other properties necessary for grid layout. You can also use `d-grid` when you just need to set `display: grid`.
