### ISSUE TITLE
Invalid certificate on the webpage

### ISSUE THREAD

**Issue by torbjornvatn** [mojocss/mojocss#3]
I get a warning when I try to access the mojocss.com webpage

<img width="490" alt="Screenshot 2024-02-08 at 11 15 32" src="https://github.com/mojocss/mojocss/assets/4453/df4899e1-037d-43e5-8fca-69a2047f7736">

**Comment by ali-m97** [comment]
Hi,
Do you have this problem on https?
We have already done http to https redirection

**Comment by torbjornvatn** [comment]
Hmm, now it works just fine 🤷🏼
