### ISSUE TITLE
Issue with media query ordering when using patterns

### ISSUE THREAD

**Issue by cyface** [mojocss/mojocss#5]
Hello!
  There appears to be an issue with the order that media query breakpoints are generated when they are specified via a pattern.

 For example:
 
```
 mojo({
    patterns: {
        '.listings': {
            'idle': 'grid-gap-1rem',
            'sm': 'cols-4',
            'md': 'cols-5',
            'lg': 'cols-6'
        },
    }
})
```

This will always output the media queries in reverse order (largest to smallest), which causes them not to take effect correctly.

If you do this:

`<div class="listings" sm="cols-4" md="cols-5" lg="cols-6">`

It generates the queries in the right order, and everything works as desired.

Changing the order of the variants in the pattern does not affect the output order in the generated CSS, it's always in reverse order.

If I remove [this reverse()](https://github.com/mojocss/mojocss/blob/e4aaeed094a228d31e7db324ded7234176208e80/src/core/builders/pattern.js#L328) things work as expected.

And just to be clear, I am using the default breakpoints; and haven't changed them.

**Comment by ali-m97** [comment]
Hello
The problem was solved
Thank you
