### ISSUE TITLE
Question about the "Size matters" part of the intro blogpost

### ISSUE THREAD

**Issue by OmidNejadabbasi** [mojocss/mojocss#8]
In [this blogpost](https://mojocss.com/blog/introducing-mojocss/) this part: 

> Size Matters
We understand the importance of a lightweight framework. Mojo weighs in at only ~50kb minified and a mere ~15kb gzipped. It's a powerhouse in a small package.

Do you also ship that 15kb to production or you only create the ouput css file ?

**Comment by mimze** [comment]
Mojo doesn't generate any css files. You only ship the 15kb(gzipped) file.

**Comment by OmidNejadabbasi** [comment]
It would be really awesome if it did generate only the needed styles like tailwind. :)
 anyway, I am closing this issue.

**Comment by mimze** [comment]
Arbitrary selectors, dynamic values, and... won't be possible in static CSS files.

We plan to add SSR support in the next release, which will be a great option for those concerned about memory overhead.

A CLI for static CSS files is also in the works for the near future.

I'm keeping it open just in case you have any questions.

**Comment by liigo** [comment]
I alse don't think that, 15KB js is better than any small .css file. 15KB mojocss is too big for me.
